# Infos du projet (depuis SonarCloud)
sonar.projectKey=khawlamt_first-laravel-project
sonar.organization=khawlamt
sonar.projectName=Laravel Todo App
sonar.projectVersion=1.0
 
# Dossiers à analyser
sonar.sources=app,routes,database
sonar.tests=tests
 
# Langage
sonar.language=php
 
# Rapport de couverture PHPUnit
sonar.php.coverage.reportPaths=coverage.xml
 
# Exclusions
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**
 
# Encodage
sonar.sourceEncoding=UTF-8
 
# URL SonarCloud
sonar.host.url=https://sonarcloud.io
 
# Token d'authentification
sonar.login=940253ffb8a6302a15b6ac2fd49a2287b6df0588